# this file has to be on same directory  level as "arcs"
site_name: Aerocae Robotics Control Suite
docs_dir: 'arcs'
theme: readthedocs
nav:
  - Introduction: docs/introduction.md
  - Installation: docs/installation.md
  - Configuration: docs/configuration.md
  - Controllers: code/helloworld2.ipynb
  - Robots: docs/robots.md
  - About: docs/about.md
  - Extending this documentation: docs/mkdocsinfo.md
plugins:
    - mkdocs-jupyter: # to display jupyternotebooks and python code
        include_source: True